language: node_js
sudo: false
cache:
  directories:
    "node_modules"

node_js:
  - "5"

before_script:
  - npm run lint
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
