language: node_js
sudo: false
cache:
  directories:
    "node_modules"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      
node_js:
  - "5"

before_install:
  - npm install -g npm

before_script:
  - npm run lint
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
